# GEOG5003M: Report

## Project introduction:
The UK Government has set a target for 1.5 million homes to be built over the course of the current parliament. Councils have been given substantially different targets to reach based partly on their degree of urbanisation (Jones Lang LaSalle IP, Inc, 2024). This leads to high spatial heterogeneity in the rates and amounts of housebuilding nationwide (Ministry of Housing, Communities and Local Government, 2025).
One approach used by councils to reach their target is to push developments where the public and private sectors collaborate, providing both public benefit and a profitable private enterprise. A portion of homes in these developments are affordable, owned by housing associations, and are an alternative to council homes. However, with the Government emphasising the more equitable social rent over affordable rent, schemes are less profitable for housing associations. Social rents are often lower than affordable rent, which is simply 80% of the market average. This leads to a selective approach by housing associations.
One priority for housing developers is the presence of housing associations, as projects they support align better with local economic and social policy and are more likely to be granted planning permission. Since housing association presence is highly heterogenous, it is important to understand the relationship between residential sales (profitability) and the number of affordable homes, which areas are the most and least supported, and where the social benefit of housing developments will be most felt. This study focusses on the Yorkshire and Humber region.
## Data introduction:
The opensource datasets for this project come from the Office for National Statistics (ONS) and the Regulator of Social Housing, accessed from the NOMIS, ONS and Open Geography Portal websites. The Statistical Data Return (SDR) 2024 survey (Regulator of Social Housing, 2024) survey is undertaken annually by English housing associations, recording the number of different property types owned per association per council. The statistical bulletin 'Housing Affordability in England and Wales: 2024' (Office for National Statistics, 2024a) includes a record of residential properties sold per council. The September 2022 - 2023 year was chosen to match the third dataset (Office for National Statistics, 2025), examining the contribution to GDP at different administrative levels. The 2023 council boundaries were downloaded from the Open Geography Portal (Office for National Statistics, 2024b).
## Code introduction:
For both non-spatial and data, the code for this project reads in datasets, pre-processes (tidies) them, joins them to other datasets and visualises them via appropriate channels. Each code block is explained in markdown and each line is explained by comments.
